# This is a basic workflow to help BAND get started with Actions

name: BAND Framework CI

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the "main" and "develop" branches
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

  # Allows one to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      # Checks the URLS in md files
      - name: URL Checker
        uses: paramt/url-checker@master
        with:
          files: "README.md,software/README.md,resources/README.md,resources/sdkpolicies/README.md,resources/sdkpolicies/bandsdk.md,resources/sdkpolicies/template.md,resources/dev_guide/git_instructions_for_submodules.md"
          blacklist: https://doi.org/10.1088/1361-6471/abf1df,BMEX-bandsdk.md,Taweretbandsdk.md,SAMBAbandsdk.md,brickbandsdk.md,surmisebandsdk.md,frescoxbandsdk.md,template.md,bandsdk.md,parmoo-bandsdk.md,foobandsdk.md,PUQ-bandsdk.md
